title: IT English Vault
description: Digital Hub for Theory and Resources.
remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: dark
aux_links:
  "Submit on Aules": "https://aules.edu.gva.es"
